import { IDRCase } from "@/lib/types";

export const idrCases: IDRCase[] = [
  {
    id: "idr_2026_014",
    externalNoticeId: "IRS-LB&I-7742",
    authority: "IRS",
    jurisdiction: "United States",
    auditType: "Transfer Pricing",
    legalEntity: "FAM Holdings US Inc.",
    receivedDate: "2026-05-04",
    taxPeriod: "FY2024",
    ownerTeam: "Audit Response Office",
    status: "in_review",
    priority: "critical",
    executiveSummary:
      "IDR package requests support for intercompany services charges, legal entity ownership, and system-to-ledger reconciliation with regulator-facing narrative and attachment traceability.",
    questions: [
      {
        id: "q_014_01",
        sequenceNumber: 1,
        title: "Intercompany services methodology",
        normalizedText:
          "Provide the methodology, calculations, and supporting agreements used to determine the 2024 intercompany management service charge.",
        intent: "Methodology support",
        status: "in_review",
        riskLevel: "critical",
        confidence: 0.92,
        sourcePageNumbers: [2, 3],
        ownerTeams: ["Tax", "Finance Controllership"],
        evidenceGap: "Awaiting signed amendment to service agreement.",
        reviewRequired: true,
      },
      {
        id: "q_014_02",
        sequenceNumber: 2,
        title: "Ledger reconciliation",
        normalizedText:
          "Reconcile the services allocation ledger extract to the filed local entity trial balance and identify reconciling items.",
        intent: "Reconciliation",
        status: "awaiting_evidence",
        riskLevel: "high",
        confidence: 0.88,
        sourcePageNumbers: [4],
        ownerTeams: ["Finance Operations", "ERP Data"],
        evidenceGap: "APAC ledger extract still in validation.",
        reviewRequired: true,
      },
      {
        id: "q_014_03",
        sequenceNumber: 3,
        title: "Beneficiary entity support",
        normalizedText:
          "Identify the legal entities receiving benefit from the shared service model and describe the operational activities performed.",
        intent: "Entity mapping",
        status: "planned",
        riskLevel: "medium",
        confidence: 0.84,
        sourcePageNumbers: [5],
        ownerTeams: ["Tax", "HR Operations"],
        evidenceGap: "Need updated org chart and service catalog.",
        reviewRequired: false,
      },
    ],
    strategy: {
      id: "strat_014_01",
      objective:
        "Substantiate arm's-length support for the management service charge with a direct narrative anchored to signed agreements, charge calculations, and legal-entity level ledger proof.",
      regulatorConcern:
        "The authority appears focused on whether the charge basis is contemporaneous, consistently applied, and demonstrably tied to benefited entities.",
      responsePosture: "direct",
      requiredEvidence: [
        "Signed intercompany services agreement and 2024 amendment",
        "Charge calculation workbook with driver-level support",
        "Entity-level ledger extract and trial balance tie-out",
        "Service catalog and beneficiary org mapping",
      ],
      ownerTeams: ["Tax", "Finance Controllership", "ERP Data"],
      approvalRoles: ["Audit Lead", "Transfer Pricing Reviewer", "Legal Reviewer"],
      riskFlags: [
        "Missing signed amendment for Q1 period",
        "One jurisdiction uses alternate cost center mapping",
      ],
      assumptions: [
        "OECD support package can be cited internally but not attached externally.",
        "Q1 amendment execution date can be explained through board approval minutes.",
      ],
      draftingGuidance: [
        "Lead with documented policy and contract basis before numeric detail.",
        "Cite every claim to a specific workbook tab, contract page, or ledger source.",
        "Call out any provisional items in a caveat block rather than burying them.",
      ],
    },
    tasks: [
      {
        id: "task_201",
        title: "Validate signed agreement lineage",
        taskType: "document_review",
        assignedTeam: "Legal Operations",
        assignedTo: "R. Singh",
        dueDate: "2026-05-26",
        priority: "critical",
        status: "blocked",
        blockerReason: "Awaiting countersigned PDF from contract archive.",
      },
      {
        id: "task_202",
        title: "Reconcile ledger extract to TB",
        taskType: "reconciliation",
        assignedTeam: "Finance Operations",
        assignedTo: "M. Alvarez",
        dueDate: "2026-05-27",
        priority: "high",
        status: "in_progress",
      },
      {
        id: "task_203",
        title: "Map beneficiary entities to service owners",
        taskType: "entity_mapping",
        assignedTeam: "Tax",
        assignedTo: "J. Patel",
        dueDate: "2026-05-29",
        priority: "medium",
        status: "ready",
      },
      {
        id: "task_204",
        title: "Draft regulator-facing response narrative",
        taskType: "drafting",
        assignedTeam: "Audit Response Office",
        assignedTo: "K. Morgan",
        dueDate: "2026-05-30",
        priority: "high",
        status: "not_started",
      },
    ],
    evidence: [
      {
        id: "ev_301",
        title: "2024 intercompany services agreement",
        type: "contract",
        sourceSystem: "Contract Archive",
        ownerTeam: "Legal Operations",
        status: "validated",
        freshness: "Current",
        legalEntity: "FAM Holdings US Inc.",
        period: "FY2024",
        sourceRef: {
          label: "Agreement recital",
          page: "PDF p.12",
          excerpt: "Specifies management service cost pool and markup policy.",
        },
      },
      {
        id: "ev_302",
        title: "Charge calculation workbook v3",
        type: "spreadsheet",
        sourceSystem: "SharePoint Finance",
        ownerTeam: "Finance Controllership",
        status: "collected",
        freshness: "Updated 2 days ago",
        legalEntity: "FAM Shared Services BV",
        period: "FY2024",
        sourceRef: {
          label: "Driver allocation tab",
          page: "Sheet Alloc_Drivers",
          excerpt: "Headcount and ticket volume drivers by service tower.",
        },
      },
      {
        id: "ev_303",
        title: "APAC entity ledger extract",
        type: "system_extract",
        sourceSystem: "SAP S/4",
        ownerTeam: "ERP Data",
        status: "requested",
        freshness: "Pending refresh",
        legalEntity: "FAM APAC Pte. Ltd.",
        period: "FY2024",
        sourceRef: {
          label: "GL export request",
          page: "Request #8841",
          excerpt: "Ledger pull queued for source period 2024-01 through 2024-12.",
        },
      },
    ],
    reviews: [
      {
        id: "rev_401",
        stage: "Strategy",
        owner: "Transfer Pricing Reviewer",
        decision: "approved_with_notes",
        dueDate: "2026-05-24",
        note: "Approved with direction to separate provisional Q1 support from final Q2-Q4 narrative.",
      },
      {
        id: "rev_402",
        stage: "Evidence sufficiency",
        owner: "Audit Lead",
        decision: "needs_more_evidence",
        dueDate: "2026-05-27",
        note: "Do not progress package until countersigned amendment and APAC tie-out are attached.",
      },
      {
        id: "rev_403",
        stage: "Draft narrative",
        owner: "Legal Reviewer",
        decision: "queued",
        dueDate: "2026-05-30",
        note: "Pending once caveat language is updated.",
      },
    ],
    submissionPackage: {
      id: "pkg_014_a",
      exportFormat: "Regulator PDF + attachment index",
      attachmentCount: 11,
      approvals: ["Audit Lead", "Tax Director"],
      status: "in_preparation",
      packageReadiness: "78% complete",
    },
    timeline: [
      {
        label: "IDR received",
        date: "2026-05-04",
        detail: "Upload and metadata intake completed.",
        tone: "info",
      },
      {
        label: "Question set confirmed",
        date: "2026-05-06",
        detail: "3 questions confirmed from OCR extraction.",
        tone: "success",
      },
      {
        label: "Strategy approved",
        date: "2026-05-11",
        detail: "Transfer pricing reviewer approved with notes.",
        tone: "success",
      },
      {
        label: "Evidence gap raised",
        date: "2026-05-21",
        detail: "Missing countersigned amendment and APAC ledger extract.",
        tone: "critical",
      },
    ],
  },
];

export const primaryCase = idrCases[0];
